#数据库ip
MYSQL_HOST = 127.0.0.1
#数据库账号
MYSQL_USER = root
#数据库密码
MYSQL_PASSWORD = whb18772916901
#redis地址
REDIS_HOST = 127.0.0.1
#redis密码 mac:123456
REDIS_PASSWORD = 123456
#邮箱授权码保存密钥
MAIL_CREDENTIAL_SECRET = whb18772916901ascsgsds
#是否开启邮件发送功能
MAIL_VERIFICATION_ENABLED = true
#smtp地址
SMTP_HOST = smtp.qq.com
#smtp端口
SMTP_PORT = 465
#smtp发件人邮箱
SMTP_USERNAME = 1289066006@qq.com
#邮箱授权码
SMTP_PASSWORD = kdhbqfnrlvpshjjc
#七牛cos存储相关配置
OSS_QINIU_ACCESS_KEY = gmU3fgKgiJYF4MsZUaKIWu47roQbYFwrXCAmGDxG
OSS_QINIU_SECRET_KEY = QOe_P_pQg7THeRetMMTNO_ZplkusHOlukej_KIIg
OSS_QINIU_BUCKET_NAME = codehub-wu
OSS_QINIU_DOMAIN = https://oss.wuhobin.top/
OSS_QINIU_BASE_PATH = base/
