spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/nexora-admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      database: 12
      #password: ${REDIS_PASSWORD}
      client-type: lettuce
      lettuce:
        pool:
          # 最大活跃链接数 默认8
          max-active: 8
          # 最大空闲连接数 默认8
          max-idle: 8
          # 最小空闲连接数 默认0
          min-idle: 0

# knife4j Basic 认证（环境相关：dev/prod 账号密码不同）
knife4j:
  basic:
    enable: true
    # Basic 认证用户名
    username: root
    # Basic 认证密码
    password: 123456

# ============================== 文件存储配置 ==============================
dromara:
  x-file-storage:
    # 默认使用的存储平台
    default-platform: qiniu-kodo-1
    # 缩略图后缀，例如【.min.jpg】【.png】
    thumbnail-suffix: ".min.jpg"
    # 七牛云 Kodo
    qiniu-kodo:
      - platform: qiniu-kodo-1
        enable-storage: true
        access-key: ${OSS_QINIU_ACCESS_KEY}
        secret-key: ${OSS_QINIU_SECRET_KEY}
        bucket-name: ${OSS_QINIU_BUCKET_NAME}
        domain: ${OSS_QINIU_DOMAIN}
        base-path: ${OSS_QINIU_BASE_PATH}

# ============================== 日志配置 ==============================
logging:
  file:
    path: /app/logs
