import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

async function readSource(relativePath) {
  return readFile(new URL(`../${relativePath}`, import.meta.url), 'utf8')
}

const apiSource = await readSource('src/api/system/config.ts')
const pageSource = await readSource('src/views/system/config/index.vue')
const systemFormSource = await readSource('src/views/system/config/components/SystemConfigForm.vue')
const registerFormSource = await readSource('src/views/system/config/components/RegisterConfigForm.vue')
const loginFormSource = await readSource('src/views/system/config/components/LoginConfigForm.vue')
const passwordFormSource = await readSource('src/views/system/config/components/PasswordConfigForm.vue')
const emailFormSource = await readSource('src/views/system/config/components/EmailConfigForm.vue')
const publicStoreSource = await readSource('src/store/modules/publicConfig.ts')
const passwordPolicySource = await readSource('src/utils/password-policy.ts')
const userPageSource = await readSource('src/views/system/user/index.vue')

test('configuration API exposes fixed group endpoints without generic CRUD', () => {
  assert.match(apiSource, /type ConfigGroupCode = 'system' \| 'register' \| 'login' \| 'password' \| 'email'/)
  assert.match(apiSource, /interface ConfigValueByGroup/)
  assert.match(apiSource, /url:\s*'\/sys\/config-group\/list'/)
  assert.match(apiSource, /url:\s*'\/sys\/config-group\/public'/)
  assert.match(apiSource, /\/sys\/config-group\/\$\{groupCode\}/)
  assert.match(apiSource, /url:\s*'\/sys\/config-group\/refresh'/)
  assert.match(apiSource, /url:\s*'\/sys\/config-group\/test-email'/)
  assert.match(apiSource, /testConfigEmailApi\(to: string\)[\s\S]*params:\s*\{ to \}/)
  assert.doesNotMatch(apiSource, /addConfigApi|deleteConfigApi|SysConfigRecord|configKey/)
})

test('configuration page uses five dedicated group forms and whole-group save', () => {
  assert.match(pageSource, /SystemConfigForm/)
  assert.match(pageSource, /RegisterConfigForm/)
  assert.match(pageSource, /LoginConfigForm/)
  assert.match(pageSource, /PasswordConfigForm/)
  assert.match(pageSource, /EmailConfigForm/)
  assert.match(pageSource, /:label="tab\.groupName"/)
  assert.match(pageSource, /label-position="right"/)
  assert.match(pageSource, /:label-width="labelWidths\[activeGroup\]"/)
  assert.match(pageSource, /system:\s*'120px'[\s\S]*register:\s*'120px'[\s\S]*login:\s*'180px'[\s\S]*password:\s*'150px'[\s\S]*email:\s*'120px'/)
  assert.match(pageSource, /max-width:\s*660px/)
  assert.match(pageSource, /max-width:\s*400px/)
  assert.match(pageSource, /:deep\(\.el-textarea\)/)
  assert.match(pageSource, /:deep\(\.el-form-item__label\)[\s\S]*white-space:\s*nowrap/)
  assert.match(pageSource, /:deep\(\.el-input-number\)\s*\{[\s\S]*width:\s*240px/)
  assert.match(pageSource, /:deep\(\.el-input-number \.el-input__inner\)[\s\S]*text-align:\s*left/)
  assert.match(pageSource, /:deep\(\.el-input-number__decrease\)[\s\S]*right:\s*28px/)
  assert.match(pageSource, /:deep\(\.el-input-number__increase\)[\s\S]*right:\s*8px/)
  assert.doesNotMatch(pageSource, /name: '系统配置'|name: '注册配置'|name: '登录配置'|name: '密码配置'/)
  assert.match(systemFormSource, /defineModel<SystemConfig>/)
  assert.match(registerFormSource, /defineModel<RegisterConfig>/)
  assert.match(loginFormSource, /defineModel<LoginConfig>/)
  assert.match(passwordFormSource, /defineModel<PasswordConfig>/)
  assert.match(emailFormSource, /defineModel<EmailConfig>/)
  assert.match(systemFormSource, /v-model\.trim="model\.siteName"/)
  assert.match(systemFormSource, /:max="0\.3"/)
  assert.match(systemFormSource, /\(model\.watermarkOpacity \* 100\)\.toFixed\(0\)/)
  assert.match(systemFormSource, /v-model="model\.watermarkType" style="width: 200px"/)
  assert.match(systemFormSource, /v-model\.trim="model\.watermarkCustomText"[\s\S]*style="width: 300px"/)
  assert.match(systemFormSource, /:disabled="model\.watermarkType !== 'custom'"/)
  assert.doesNotMatch(systemFormSource, /<el-form-item v-if="model\.watermarkEnabled"/)
  assert.doesNotMatch(systemFormSource, /show-input/)
  assert.match(registerFormSource, /v-model="model\.verifyEmail"/)
  assert.match(loginFormSource, /v-model="model\.maxRetryCount"/)
  assert.doesNotMatch(loginFormSource, /controls-position/)
  assert.match(passwordFormSource, /v-model="model\.requireSpecial"/)
  assert.match(emailFormSource, /v-model="model\.port"[\s\S]*:min="1"[\s\S]*:max="65535"/)
  assert.match(emailFormSource, /v-model="model\.password"[\s\S]*type="password"[\s\S]*show-password/)
  assert.match(emailFormSource, /testConfigEmailApi\(testEmailAddress\.value\)/)
  assert.match(pageSource, /updateConfigGroupApi\('system', forms\.system\)/)
  assert.match(pageSource, /updateConfigGroupApi\('email', forms\.email\)/)
  assert.match(pageSource, /refreshConfigGroupCacheApi\(\)/)
  assert.match(pageSource, /sys:config:update/)
  assert.doesNotMatch(pageSource, /as never/)
  assert.doesNotMatch(pageSource, /sys:config:add|sys:config:delete|分页|搜索/)
})

test('public configuration drives branding, password policy, and pending-user audit', () => {
  assert.match(publicStoreSource, /getPublicConfigApi\(\)/)
  assert.match(publicStoreSource, /applyDocumentTitle/)
  assert.match(passwordPolicySource, /Array\.from\(password\)\.length/)
  assert.match(passwordPolicySource, /TextEncoder\(\).*72/s)
  assert.match(passwordPolicySource, /\\p\{Lu\}/)
  assert.match(passwordPolicySource, /\\p\{Ll\}/)
  assert.match(passwordPolicySource, /\\p\{Nd\}/)
  assert.match(passwordPolicySource, /requireUppercase/)
  assert.match(passwordPolicySource, /requireLowercase/)
  assert.match(passwordPolicySource, /requireNumber/)
  assert.match(passwordPolicySource, /requireSpecial/)
  assert.match(userPageSource, /row\.status === 2/)
  assert.match(userPageSource, /审核通过/)
  assert.match(userPageSource, /auditUserApi\(row\.id\)/)
})
