#数据库ip
mysql.address = ${MYSQL_HOST:127.0.0.1}
#数据库账号
mysql.username = ${MYSQL_USER:root}
#数据库密码 whb18772916901
mysql.password = ${MYSQL_PASSWORD:123456}
#redis地址
redis.address = ${REDIS_HOST:127.0.0.1}
#redis密码 mac:123456
redis.password = ${REDIS_PASSWORD:123456}
